package cn.com.chenyixiao.rrs.entity;
// Generated 2016-4-6 18:18:32 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Restaurant generated by hbm2java
 */
@Entity
@Table(name = "restaurant", catalog = "rrs")
public class Restaurant implements java.io.Serializable {

	private long id;
	private String name;
	private String category;
	private String region;

	public Restaurant() {
	}

	public Restaurant(long id) {
		this.id = id;
	}

	public Restaurant(long id, String name, String category, String region) {
		this.id = id;
		this.name = name;
		this.category = category;
		this.region = region;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "region", length = 45)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

}
